repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 9a790d2bbf52124eecb5a71a4bab4884804ffa2a # v1.100.0
    hooks:
      - id: terraform_fmt
        args:
          - --hook-config=--tf-path=tofu
      - id: terraform_validate
        args:
          - --hook-config=--tf-path=tofu
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--tf-path=tofu
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --hook-config=--tf-path=tofu

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=100']
      - id: check-merge-conflict
      - id: detect-private-key
